### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by RF77** [RF77/comfobox-mqtt#11]
To use it on Linux and Mac, the libs should be Mono compatible.

Known issues: 
- ColoredConsoleAppender

**Comment by RF77** [comment]
Added the [Mono compatibility test](https://rawgit.com/RF77/comfobox-mqtt/master/docs/Mono/MoMA%20Scan%20Results.html)

**Comment by hardlog** [comment]
Hallo,
unter Win läuft es gut. Würde es gerne unter mono auf einem RaspPi laufen lassen. Weiter als du bin ich mit den gelisteten Problemen nicht gekommen. ColoredConsoleAppender -> ConsoleAppender. Nächst Meldung ist bei mir "Missing method Run in assembly /home/pi/ComfoBox/ComfoBoxMqttConsole.exe, type Nito.AsyncEx.AsyncContext".
Bist du derweilen veileicht schon weiter gekommen?

Gruß hardlog

**Comment by RF77** [comment]
Hallo hardlog,
Nein, bin nicht weitergekommen. Ist nicht einfach, da ich nur eine Linux VM habe und kein Raspberry PI. Kann es also gar nicht so einfach testen. Zudem habe ich selber im Moment kein Bedürfnis dazu, noch grosse Linux Erfahrungen. Das mit dem ColoredConsoleAppender ist einfach -> Einfach normalen ConsoleAppender für log4net konfigurieren (siehe .config Datei)
Bezüglich AsyncContext habe ich keine Ahnung...
Kann Dir im Moment also nicht weiterhelfen. -> Deshalb das "help_wanted" Label auf diesem Issue.

Grüsse

**Comment by RF77** [comment]
Funktioniert nun mit meinem gerade angeschafften Raspberry PI (Siehe Bild im Readme.txt). Release wird später folgen...

**Comment by RF77** [comment]
Sollte ab der Version 0.4.0 nun funktionieren.
